### ISSUE TITLE
what is the output directory

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [Dapzer/image-viewer#2]
`Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings`

**Comment by dapzer** [comment]
Are you sure that the problem is on the side of this package?

**Comment by MohammadTaseenKhan** [comment]
No no not the package side , I just can't figure out which directory is the output directory during deployment on vercel

**Comment by MohammadTaseenKhan** [comment]
On which framework is this project on ??

**Comment by dapzer** [comment]
It's react. I think you trying clone this repo and deploy on vercel?

**Comment by MohammadTaseenKhan** [comment]
yes  Can you please check why the deployment is showing error

**Comment by dapzer** [comment]
You can not because this is npm package, not a regular site
